### ISSUE TITLE
error callback if publishing or subscribing failed due to hardware issues

### ISSUE THREAD

**Issue by webpipl** [opentok/web-components#8]
Vonage video web components

1. While using Vonage web components, I was unable to get errors if subscribing failed.

2. How do I show my name while the Vonage video is playing? 

3. I couldn't use streamCreated because the inside vonage-subscriber component method was gaining access. 

 4. Publishing might be get failed , due to permissions or hardware issues , how can i get those errors to display

`streamCreated: (event) => {
	const subscriberOptions = {
	insertMode: 'append',
	width: this.width,
	height: this.height
	};
	this.session.subscribe(event.stream, document.querySelector('video-subscribers'), subscriberOptions, (error) => {
	if(error){
	console.error("error subscribing to session: ", error);
	}
	});
	}`

**Comment by conshus** [comment]
Hey @webpipl  Thanks for this.

1. That's a good point. I'm going to add an error event that you will be able to listen for in the components. I added it to the new <video-subscriber>

2. I was thinking about adding a `properties` to <video-publisher> so that you can set all the stuff in the properties for the initPublisher method: https://tokbox.com/developer/sdks/js/reference/OT.html#initPublisher which includes `name`. Question: do you think that width and height should still be separated or included in `properties`?

3. You beat me before I could add the <video-subscriber> component. haha 
- <video-subscribers> was meant to be an element where you just place it in your markup and it will handle adding the subscribers so you don't have to worry about anything.

- <video-subscriber> would be if you wanted more control of where and how subscribers are inserted. Like if someone is sharing their screen, you can then detect that with streamCreated and place that stream at the top and make it larger.

I can see having an event fired in <video-subscribers> for `streamCreated` could be useful so I can add that also.

4. Goes with 1 so I'll be adding an `error` event that you can listen for on the component

Thanks again for the feedback and keep them coming. 

We really want to make these Web Components as useful for developers as possible.

How are you finding the Web Components so far?
Are you using them in a Framework/Library?

**Comment by webpipl** [comment]
Thank you for your response. Iam using it in ReactJs  I knew from your github that no articles were still published; in fact,

1. I was surprised to see that you were making a session connection while adding the publisher and subscriber while I was digging through the library.

2. You've already added a few events to the session; is it possible to register the same event from the developer?  >> VideoPublisher.js **25 ** line

3. Correct me if I'm wrong, but do we have to leave the session connection to the developer's discretion, sir? Because you're doing session connect while creating a subscriber again, it displays a session already connected warning.

**Comment by conshus** [comment]
Yeah, we are still working on getting the Web Components in a good place before we start announcing it, so that's why it's really helpful to get feedback now.

> I was surprised to see that you were making a session connection while adding the publisher and subscriber while I was digging through the library.

Not sure what you mean? Are you referring to `this.session.connect(this.token);` being in < video-publisher > and < video-subscribers >? I was thinking there could be a use case where the < video-subscribers > was the only component on the page, for example, just for viewers of the chat. There would be no < video-publisher >. Does this also cover your question 3?

> You've already added a few events to the session; is it possible to register the same event from the developer? >> VideoPublisher.js **25 ** line

Do you mean adding `eventHandlers` like with the React components https://github.com/opentok/opentok-react#otpublisher-component? If so, the yes, that was also requested by someone else. How are you using the `eventHandlers`? So that I can try and make sure it's useful to you as well.

> Correct me if I'm wrong, but do we have to leave the session connection to the developer's discretion, sir? Because you're doing session connect while creating a subscriber again, it displays a session already connected warning.

Are you referring to < video-subscriber >? There shouldn't be a session.connect in there. If you are talking about < video-subscribers >, I think I answered that above. In my mind, it's either < video-subscribers > OR < video-subscriber >, not both. < video-subscriber > gives the developer more control of how and where the Subscriber shows up. So if it's by itself on a page, I'm thinking you would need to write the code to connect to the session so that the page can listen for the `streamCreated`, `streamDestroyed`, etc events. I haven't tried that yet though. 

My goal for the Web Components is to try and abstract as much from the developer to try and make it as easy as putting a regular HTML element and passing in some attributes and listening for some events.

Let me know if these answered your questions. If you have anything else, please let me know.

I'll be making updates this and next week.

Thanks.
